plugins {
    id 'java'
    id 'maven-publish'
    id 'com.gradleup.shadow' version '9.3.1'
}

group = 'org.vindicterra'
version = '0.2.3-dev'

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/Vindicterra/vindicterra-lib")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        url 'https://repo.xenondevs.xyz/releases'
    }
    maven {
        url 'https://jitpack.io/'
    }
    maven { url 'https://repo.momirealms.net/releases/' }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")

    //compileOnly "com.github.LoneDev6:API-ItemsAdder:3.6.3-beta-14"

    compileOnly 'net.momirealms:craft-engine-core:0.0.67'
    compileOnly 'net.momirealms:craft-engine-bukkit:0.0.67'

    implementation 'org.apache.commons:commons-lang3:3.8.1'
    implementation 'commons-lang:commons-lang:2.4'

    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

build {
    dependsOn tasks.shadowJar
}

shadowJar {
    configurations = [project.configurations.runtimeClasspath]
    archiveClassifier = ''
}