name: VindicterraLib
version: '$version'
main: net.vindicterra.vindicterralib.VindicterraLib
api-version: '1.21'
load: STARTUP
description: Vindicterra Standard Library
depend:
  - CraftEngine
permissions:
  vindicterralib.admin:
    default: op
    description: Allows you to access admin commands or features
    children:
      - vindicterralib.admin.cooldown-bypass
